### ISSUE TITLE
Problem bei der Installation 

### ISSUE THREAD

**Issue by rayigen85** [nielstron/pyfronius#12]
Hallo,
ich habe versucht das Modul mittels pip zu installieren (pip install pyfronius). Leider erhalte ich eine Fehlermeldung:
```
Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: 'C:\\Users\\xxxx\\AppData\\Local\\Temp\\pip-req-build-qa47je68\\pyfronius/tests/test_structu
re/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData'
```

Ich habe Python 3.7.4 und versuche die Installation auf Windows 10.

Vielleicht habt ihr ja eine Idee.

**Comment by nielstron** [comment]
Hallo, es sieht so aus als wären die Namen der Dateien nicht mit den Windows Datei-Namen-Konventionen vereinbar. Das ist auf die schnelle nicht so einfach zu beheben... Aber wir können es mal für die Nachwelt stehen lassen.

ENGLISH VERSION:
It seems that there is a problem installing this package on windows because some of the filenames violate windows file naming conventions. This is not easily fixable but everyone interested is welcome to fix it.
